name: todo_list
description: "Todo list"

#ini untuk mengantur versi dari aplikasi yang kita buat
version: 1.0.0+1


environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get: ^4.6.6
  intl: ^0.19.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  geolocator: ^13.0.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^8.0.0
  get_storage: ^2.1.1
  sqflite: ^2.4.0
  path: ^1.9.0
  flutter_launcher_icons: ^0.14.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/main_icon.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

